name: Deploy

on:  
  push:
    tags:
      - '*'


jobs:
  Deploy:
    name: Deploy the new release
    runs-on: ubuntu-latest
    steps:
    - name: Release
      run: |
        echo "Run commands for deployment, 
        so something like swapping out instances in aws or helm upgrade commands, 
        maybe argocd commands depending on the deployment type"
