name: Publish in GitHub Package Registry

on:  
  push:
    tags:
      - '*'

jobs:  
  deploy:
  name: Deploy merlin-service
  runs-on: ubuntu-latest
    steps:
    - name: Commands for deployment
      run: |
        echo "Run commands for deployment, 
        so something like swapping out instances in aws or helm upgrade commands, 
        maybe argocd commands depending on the deployment type"
  