name: Terraform

on:
  push:
    branches: [ master ]
    paths:
    - 'infrastructure/**'
  workflow_dispatch:

jobs:
  environments:
    strategy:
      matrix:
        environment: ["dev", "stage", "prod"]
    steps:
      - uses: actions/checkout@v2
      - name: Get Tf
        run: echo "installing hashicorp/setup-terraform@v1 here"
      - name: Terraform Init
        run: |
          cd infrastructure/environments/${{ matrix.environment }}
          echo "I am running the tf init step"
          ls
      - name: Terraform Plan
        run: |
          cd infrastructure/environments/${{ matrix.environment }}
          echo "I am running the tf plan step with my remote state in aws"
          ls
      - name: Terraform Apply
        run: |
          cd infrastructure/environments/${{ matrix.environment }}
          echo "I am applying these changes prod being a protected branch that requires approval from code owners"
          ls
